#ENC[AES256_GCM,data:hzOjucshyNhWWH2Mr+Zg+xn3SuLjYJLNCswQ9ShPeA8g7rPwmtLK9aTgoMCLa1bZS3UWvQkYEh5RQIHUEWKSIO/UxS/vQYWRHCCcp2uI,iv:O7VYHPlLHN5Lsx4ObhianvUOZxXy7IWmizGjepAiFpU=,tag:g4WyHaIosI+wbbArGttDaQ==,type:comment]
#ENC[AES256_GCM,data:okU2pPhxeep9R1FF5DOVlya7291FatA0uRAQvxFouDHNU6M9ny/cr4P3WeTHykoJ3qbgEcTQh/RY4+dG8kcQWoCm2VrU7zp3B09WD0abFv41JS5+qvY=,iv:B8v1joMDgvgaxuDhAfmzV6PokWDHAEyY69w1GGd8iDo=,tag:xc7NnZ0BqLTUuyr4JSZ2eQ==,type:comment]
apiVersion: ENC[AES256_GCM,data:/qk=,iv:RbPU2wyG4vgdWeZpjNcSq1SHABK7S4jWMbGzBKrQSH8=,tag:RrX1tKt5Ea6KJNkn4b3hkw==,type:str]
kind: ENC[AES256_GCM,data:FAk0IHem,iv:N9g4mBHFNwitNlNLeGMcEK3+tHqjVXEEPXH37wKpsak=,tag:SxsSL+xwqGF67VMX9GrYqg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:eYlATG2lQbFb7nA8bbknH5x37hg=,iv:h0/wpRrsfIMFUnUMi1HR0rXcBXDFlGTdwJoJqfmfn28=,tag:9jTOaUVYCbuMe1W/6m+EHg==,type:str]
    namespace: ENC[AES256_GCM,data:nMGmsQ5i8QXmBA==,iv:blgCkN5gctVSesk+VXmAnVRUEz8U5NMvAYz+xENzdv4=,tag:egqpAx1yG0ZLzGr87KcoyA==,type:str]
stringData:
    adminUser: ENC[AES256_GCM,data:qdVREFs=,iv:eSqVZhDbc/TslFrdv5VA58rWEbBdaa3X5ij2GQcNxfE=,tag:uFTurYGkRujBq1AfQHwjvA==,type:str]
    adminPassword: ENC[AES256_GCM,data:yClPerrSk6owUOscdteYjuGjUwf0+hoyuQ==,iv:xW6BolALdPO2FGH8atqfPaYudmfTxPYSYHryF8jGm9M=,tag:Fak7yUhIwjn3iFPbuuZqZA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4VUZoYittK0tCdmxwMjdC
            M052bnFFU3VWMVFoNm9IT1JaZ0dYbkE3ZEhNCjY2RGpWL2gycHB6ZHdaVzdiRlhS
            OGlCK2FJQ3hFNDh4MitBcWFrVU12NnMKLS0tIExGRjJzQXFxaDl3aCtkZzR1VzRm
            Qkc3SGh6NGpQVzhPZlNVbXpqZUNiQmsK5dM08VgGIaufClvPWWlhG+hhcBUBVhX9
            RPWmv0wTjwoxAQhKaCOCjheyr2p/bjiKzdG/WLSqmi/SWvR5xO8bmA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sg49qgvaxgvgxt8ht540knum5zgklcqp220j7yl375xqsldvyfwszl252u
    lastmodified: "2026-05-16T10:35:17Z"
    mac: ENC[AES256_GCM,data:4vzVUXkoRaKCyM1xXP5GoptnyzC1melE2eTuNw4IttTKoV8J7UbH/BDJK3dferzzYDDa3LHzHjD9Zg/2CqNKUGMiUQz/uO0vexy0LBVxaiHQ1wFKv5d+k4evFFiT8O2y5rIWH3YCzwfR2EnoFnOlezeiydC4HybLXzHh7sAYQO4=,iv:jyP1hA6C4DssOKiaKfd+MCLR8EBpSprllEYxp8meK4U=,tag:oQD3jF7HEieuBFPRXY519g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
