#ENC[AES256_GCM,data:mj5nhnJdDt9R6RLGAKjnEpbfmITYealBvH4w0I4mG6sQjwvc6fscpkE8TT36s9MQZ8t4refEIuyO,iv:WlGB1nR29k1KQLLFJBHb2e4t2GzI3OHVKZkK2l6N/o8=,tag:woilAWtujxQUy3WilM6p1g==,type:comment]
#ENC[AES256_GCM,data:0XphS7A8OgmPNyUX399Gcp8ObAk2Z0yNDnSHDvH3xBQsvAV8zxQWczgu7tBYQg==,iv:Uc+kDgHGtMKC0+5eXKudYYCZ5UX268VAQoVRS9R5Bno=,tag:xCJt80EpabFhXJDTqteprQ==,type:comment]
#ENC[AES256_GCM,data:inWrwCwm/cURt2Jw8ag436BKefSJwZOT95FETu5668CG2h5ag5beKDMdG22NZC0J5J+YejYD1ZdaNG2Yna004a/vccP5hd1CICZpmd0=,iv:iuJUilBTvBdxdODd5k8l+mCvOrhYTySQfUIJM4uZ650=,tag:TeomY+kbErnNvugxWuDEMw==,type:comment]
#
#ENC[AES256_GCM,data:M34NhKKrG5amOQPYmCgUK2mmd1KucAGLsnWkM+mNgSjZeANU++9lqTcCcQyM6g2UezHIk1mos2encwI4ersLEHQQz0IXoyiHWn6wB1ma8iQ=,iv:quWq+Yg18YSqAA8e7ksHe43qatNfIR6qnjB+IUyBVms=,tag:dzELfXDt6T2Y7CBUvaSyHQ==,type:comment]
#ENC[AES256_GCM,data:HRHq6ICEB5hergujEdLO91oodvjwhWFE0SckoqkKIZdTdip2TZfAziRQH2Gd7csGxBL6pTzdDgf9hfaBgzS6CHr1WvVIJ+yz70FfKQ==,iv:QEjEveeymu0fF5m1/EGXkDVwvtK9m6a6Ny9X4jc4+Fo=,tag:Ps59QVcRc2RLx5FFeQfrFQ==,type:comment]
apiVersion: ENC[AES256_GCM,data:GMs=,iv:nqKHmjxtrSts2gTA4CtULZ0oslkemfOD9pIKWBTIHlA=,tag:Vs9Hu1ubWBH6T9s8dUvr8w==,type:str]
kind: ENC[AES256_GCM,data:zwuxEmvp,iv:433X56wS5lXYjYZs8SkewKDeqmmPpTyy4Bm8RmZCkYk=,tag:/rzy2C+BxZZkzyJ2F7RzMQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:8bTteCNjKyt/ZfsOe9PR,iv:Qln+DYmOpy20cLB9+aymLrCFwQpvlmcKWD6trZyNwXA=,tag:I/WsPiAIVC/xI06sm3yyaQ==,type:str]
    namespace: ENC[AES256_GCM,data:9n/IasFxMzHT,iv:x0Ad+YOw6jUQtnEDXWYZ4Dp4W3iEgsXB6TuBAfB8CSw=,tag:Dv94kFtfQKuc86O2a5Cd9A==,type:str]
stringData:
    clientId: ENC[AES256_GCM,data:09cIXEUN2gX5e0Lyy/cyxnw=,iv:tjhGpADYH+Pj/WYp9xXey91iHOCiJulqln8NkRTowLA=,tag:fFYrClEQIHJdA5W3Oqi1Qg==,type:str]
    clientSecret: ENC[AES256_GCM,data:J539RiqySsMyy8D2GdrDOb39pGTs0ug1P4AJ2fS7+WX11xoZi7ab141LnvZCUj5fFQOT2NQ+1DE88ZX6iUdL,iv:yDEEOuwgTIpnpyH9mBzJUUx55XSVBCZPfpC7SDcsgM8=,tag:0tZLWSYWuf0LQkxCL/CQUA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUEtYcXZ0djdzM2xqbXlH
            QTN2NGZ1WkRKb3YrRzJwa1NCOXJFOE80Q1hFCnpoSHdwdUxQSHFxL093cE5zSHE0
            RmZhRklSUTFXL1RmVGd5RHJLMFF1Y1kKLS0tIGZuRDMwaDRvUWIwSUpLWjFiV0dG
            Y3hGZjFpUlgxRHFiU0EyMElxaThyUmsKhfNDN0QFnvQ9ba3g+t1x9U3qvmLSyrLE
            A19ci06zRsLx6xabHDMEwowzNmgSEI+OCKPP0/sMOdolhqkjW432Pg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sg49qgvaxgvgxt8ht540knum5zgklcqp220j7yl375xqsldvyfwszl252u
    lastmodified: "2026-05-15T13:04:17Z"
    mac: ENC[AES256_GCM,data:tuQ5z2odyz3Qpj853qmFV1X+2KG4ArjSl+7/ii/ZMohQK1ggahQQZTiWWIY5GOuAVJ1yB0mcM09lAQyAfvaNEeZMON/hiMzsg5/mrgkN7POjvFQoNhsYFUjsqzPXptqwDV6uSKMb4tJB9bcDOMm/wez6oQdNAX4QhWh4F0WTWu8=,iv:NewE7Bjq6ESRlj/93ChWQrlXVbNI46Au3ub5Qpn3QVc=,tag:CwlyhqalcYIQ/ppTX8t6nw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
